version: 2.1

# -------------------------------------------------------------------------------------
# Environments to run the jobs in
# -------------------------------------------------------------------------------------
cpu: &cpu
  machine:
    image: ubuntu-2004:202107-02
  resource_class: medium

gpu: &gpu
  machine:
    image: ubuntu-1604-cuda-11.1:202012-01
  resource_class: gpu.nvidia.small

version_parameters: &version_parameters
  parameters:
    pytorch_version:
      type: string
    torchvision_version:
      type: string
    pytorch_index:
      type: string
      default: "https://download.pytorch.org/whl/torch_stable.html"
    python_version:
      type: string
      default: '3.6.8'

  environment:
    PYTORCH_VERSION: << parameters.pytorch_version >>
    TORCHVISION_VERSION: << parameters.torchvision_version >>
    PYTORCH_INDEX: << parameters.pytorch_index >>
    PYTHON_VERSION: << parameters.python_version>>

# -------------------------------------------------------------------------------------
# Re-usable commands
# -------------------------------------------------------------------------------------
install_python: &install_python
  - run:
      name: Install Python
      working_directory: ~/
      command: |
        # upgrade pyenv
        cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
        pyenv install -s $PYTHON_VERSION
        pyenv global $PYTHON_VERSION
        python --version
        which python
        pip install --upgrade pip

install_dependencies: &install_dependencies
  - run:
      name: Install Dependencies
      command: |
        # disable crash coredump, so unittests fail fast
        sudo systemctl stop apport.service
        # use a lower version of setuptools to prevent potential bugs
        pip install setuptools==59.5.0
        # install the specified versions of torch and torchvision
        pip install torch==$PYTORCH_VERSION -f $PYTORCH_INDEX
        if [[ "$TORCHVISION_VERSION" == "master" ]]; then
          pip install git+https://github.com/pytorch/vision.git
        else
          pip install torchvision==$TORCHVISION_VERSION -f $PYTORCH_INDEX
        fi
        python -c 'import torch; print("CUDA:", torch.cuda.is_available())'
        # install dependencies of core-pytorch-utils
        pip install -r requirements.txt
        # install dependencies of unittests
        pip install -r tests/requirements.txt
        pip install pytest coverage

install_core_pytorch_utils: &install_core_pytorch_utils
  - run:
      name: Install Core-PyTorch-Utils
      command: |
        pip install -v -e .

run_unittests: &run_unittests
  - run:
      name: Run Unit Tests
      command: |
        python -m coverage run --branch --source cpu -m pytest tests/
        python -m coverage report
        python -m coverage html

save_unittests_results: &save_unittests_results
  - store_artifacts:
      path: htmlcov

# -------------------------------------------------------------------------------------
# Jobs to run
# -------------------------------------------------------------------------------------
jobs:
  cpu_tests:
    <<: *cpu
    <<: *version_parameters
    steps:
      - checkout
      - <<: *install_python
      - <<: *install_dependencies
      - <<: *install_core_pytorch_utils
      - <<: *run_unittests
      - <<: *save_unittests_results

  gpu_tests:
    <<: *gpu
    <<: *version_parameters
    steps:
      - checkout
      - <<: *install_python
      - <<: *install_dependencies
      - <<: *install_core_pytorch_utils
      - <<: *run_unittests
      - <<: *save_unittests_results

workflows:
  version: 2
  regular_test:
    jobs:
      - cpu_tests:
          name: cpu_tests_pytorch1.10
          pytorch_version: '1.10.0+cpu'
          torchvision_version: '0.11.1+cpu'
      - gpu_tests:
          name: gpu_tests_pytorch1.10
          pytorch_version: '1.10+cu111'
          torchvision_version: '0.11.1+cu111'